apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: store
  namespace : jhipster
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: store
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 35
  
